apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    name: nginx-ingress-lb
