apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  labels:
      name: influx-grafana
  name: influxdb-grafana
spec:
  replicas: 1
  selector:
      matchLabels:
        name: influx-grafana
  template:
    metadata:
      labels:
        name: influx-grafana
    spec:
      serviceAccountName: "io-rancher-system"
      containers:
      - name: influxdb
        image: {{ .Values.influxdb.image }}
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: {{ .Values.grafana.image }}
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb.kube-system.svc.cluster.local:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
      {{- if eq .Values.influxdb.hostPath "" }}
        emptyDir: {}
      {{- else }}
        hostPath:
          path: {{ .Values.influxdb.hostPath | quote }}
      {{- end }}
      # Some other volume types to consider
      # https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes
      - name: grafana-storage
        emptyDir: {}
